### ISSUE TITLE
[Edit Suggestion] Successful Installation, Now What Do I Do?

### ISSUE THREAD

**Issue by kaushickacademy** [modxcms/docs#127] opened 2015-12-26 15:40 UTC
## Page Title

Successful Installation, Now What Do I Do?
## URL

https://rtfm.modx.com/revolution/2.x/getting-started/installation/successful-installation,-now-what-do-i-do

**Comment by Mark-H** [comment] 2016-02-16 15:00
Appears to be waaaaaaay old and lacking images.

**Comment by Mark-H** [comment] 2016-02-16 15:29
Dupe of #35

**Closed as completed by Mark-H** 2016-02-16 15:29 UTC
